# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt_stories.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 608)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.add = QtWidgets.QPushButton(self.centralwidget)
        self.add.setGeometry(QtCore.QRect(350, 530, 121, 41))
        self.add.setObjectName("add")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(150, 10, 131, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(120, 60, 61, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(70, 210, 101, 20))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(70, 250, 151, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(90, 290, 91, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(40, 330, 161, 20))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(100, 370, 111, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(10, 410, 201, 20))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(70, 450, 101, 20))
        self.label_9.setObjectName("label_9")
        self.textTitle = QtWidgets.QTextEdit(self.centralwidget)
        self.textTitle.setGeometry(QtCore.QRect(260, 10, 321, 31))
        self.textTitle.setObjectName("textTitle")
        self.text = QtWidgets.QTextEdit(self.centralwidget)
        self.text.setGeometry(QtCore.QRect(180, 60, 481, 141))
        self.text.setObjectName("text")
        self.textAnswer = QtWidgets.QTextEdit(self.centralwidget)
        self.textAnswer.setGeometry(QtCore.QRect(180, 210, 481, 31))
        self.textAnswer.setObjectName("textAnswer")
        self.textSpectator = QtWidgets.QTextEdit(self.centralwidget)
        self.textSpectator.setGeometry(QtCore.QRect(180, 250, 481, 31))
        self.textSpectator.setObjectName("textSpectator")
        self.textOpinion = QtWidgets.QTextEdit(self.centralwidget)
        self.textOpinion.setGeometry(QtCore.QRect(180, 290, 481, 31))
        self.textOpinion.setObjectName("textOpinion")
        self.textApi = QtWidgets.QTextEdit(self.centralwidget)
        self.textApi.setGeometry(QtCore.QRect(180, 330, 181, 31))
        self.textApi.setObjectName("textApi")
        self.textProof = QtWidgets.QTextEdit(self.centralwidget)
        self.textProof.setGeometry(QtCore.QRect(180, 370, 241, 31))
        self.textProof.setObjectName("textProof")
        self.textApiMessage = QtWidgets.QTextEdit(self.centralwidget)
        self.textApiMessage.setGeometry(QtCore.QRect(180, 410, 311, 31))
        self.textApiMessage.setObjectName("textApiMessage")
        self.Ans1 = QtWidgets.QTextEdit(self.centralwidget)
        self.Ans1.setGeometry(QtCore.QRect(180, 450, 261, 31))
        self.Ans1.setObjectName("Ans1")
        self.Ans2 = QtWidgets.QTextEdit(self.centralwidget)
        self.Ans2.setGeometry(QtCore.QRect(180, 490, 261, 31))
        self.Ans2.setObjectName("Ans2")
        self.Ans3 = QtWidgets.QTextEdit(self.centralwidget)
        self.Ans3.setGeometry(QtCore.QRect(470, 450, 261, 31))
        self.Ans3.setObjectName("Ans3")
        self.Ans4 = QtWidgets.QTextEdit(self.centralwidget)
        self.Ans4.setGeometry(QtCore.QRect(470, 490, 261, 31))
        self.Ans4.setObjectName("Ans4")
        self.deleteButton = QtWidgets.QPushButton(self.centralwidget)
        self.deleteButton.setGeometry(QtCore.QRect(670, 530, 121, 41))
        self.deleteButton.setObjectName("deleteButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.add.setText(_translate("MainWindow", "Записать"))
        self.label.setText(_translate("MainWindow", "Название истории:"))
        self.label_2.setText(_translate("MainWindow", "История:"))
        self.label_3.setText(_translate("MainWindow", "Правильный ответ:"))
        self.label_4.setText(_translate("MainWindow", "Мнение очевидцев:"))
        self.label_5.setText(_translate("MainWindow", "Мнение коллег:"))
        self.label_6.setText(_translate("MainWindow", "Название api (image/map):"))
        self.label_7.setText(_translate("MainWindow", "Что ищет api?"))
        self.label_8.setText(_translate("MainWindow", "Пояснение(None по умолчанию):"))
        self.label_9.setText(_translate("MainWindow", "Варианты ответов:"))
        self.deleteButton.setText(_translate("MainWindow", "Очистить файл"))
